name: "Duplicate Guard"
description: "Blocks pull requests with unintentionally duplicated files"
author: "Chris Rutkowski"
inputs:
  ignore_file:
    description: "Path to the ignore file"
    required: true
    default: "./duplicate_guard.ignore"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        separator: ","

    - name: Run Duplicate Guard
      run: |
        files="${{ steps.changed-files.outputs.added_files }},${{ steps.changed-files.outputs.modified_files }}"
        python3 ${GITHUB_ACTION_PATH}/duplicate_guard.py ${{ inputs.ignore_file }} "$files"
      shell: bash
